#include "tools.h"
#include "file_io.h"
#include "new.h"

#include <stdio.h>
#include <stdlib.h>

const char* CUTE_INI = "; cute package manager settings\n\
[cute]\n\
version = \"0\"\n\
\n\
; your project settings\n\
[project]\n\
name = \"%s\"\n\
version = \"0.1.0\"\n\
\n\
; your project dependencies\n\
[dependencies]\n\
";

const char* CUTE_LOCK_INI = "; THIS FILE IS AUTO-GENERATED\n\
; DO NOT EDIT THIS FILE DIRECTLY\n\
";

const char* CMAKELISTS_TXT = "cmake_minimum_required(VERSION 3.10)\n\
project(%s C)\n\
\n\
set(CMAKE_C_STANDARD 11)\n\
set(CMAKE_C_STANDARD_REQUIRED ON)\n\
set(CMAKE_C_EXTENSIONS OFF)\n\
\n\
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)\n\
	set(IS_ROOT_PROJECT TRUE)\n\
else()\n\
	set(IS_ROOT_PROJECT FALSE)\n\
endif()\n\
\n\
if(IS_ROOT_PROJECT)\n\
	file(GLOB installed_packages LIST_DIRECTORIES true \"${CMAKE_CURRENT_SOURCE_DIR}/.libraries/*\")\n\
\n\
	set(PACKAGE_TARGETS \"\")\n\
\n\
	foreach(package_dir ${installed_packages})\n\
		if(IS_DIRECTORY \"${package_dir}\" AND EXISTS \"${package_dir}/CMakeLists.txt\")\n\
			add_subdirectory(\"${package_dir}\")\n\
\n\
			get_filename_component(target_name \"${package_dir}\" NAME)\n\
\n\
			list(APPEND PACKAGE_TARGETS ${target_name})\n\
		endif()\n\
	endforeach()\n\
endif()\n\
\n\
file(GLOB_RECURSE SRC \"src/*.c\")\n\
\n\
if(IS_ROOT_PROJECT)\n\
	add_executable(${PROJECT_NAME} ${SRC})\n\
\n\
	if(PACKAGE_TARGETS)\n\
		target_link_libraries(${PROJECT_NAME} PRIVATE ${PACKAGE_TARGETS})\n\
	endif()\n\
else()\n\
	add_library(${PROJECT_NAME} STATIC ${SRC})\n\
\n\
	target_include_directories(${PROJECT_NAME} PUBLIC \"${CMAKE_CURRENT_SOURCE_DIR}/src\")\n\
endif()\n\
\n\
";

const char* MAIN_C = "#include <stdlib.h>\n\
#include <stdio.h>\n\
\n\
int main(int argc, char* argv[]) {\n\
	printf(\"Hello, world!\\n\");\n\
\n\
	return EXIT_SUCCESS;\n\
}\n\
";

new_project_result_t new_project(int argc, char* argv[]) {
	char* project_name = NULL;
	for (int i = 2; i < argc; i++) {
		if (argv[i][0] != '-') {
			if (project_name != NULL)
				return PROJECT_INVALID_ARGS;

			project_name = argv[i];
			continue;
		}
	}

	if (project_name == NULL)
		return PROJECT_NO_NAME;

	char* directory = format("./%s", project_name);
	char* ini_path = format("%s/Cute.ini", directory);
	char* lock_path = format("%s/Cute.lock", directory);
	char* cmakelists_txt_path = format("%s/CMakeLists.txt", directory);

	char* src_dir = format("%s/src", directory);
	char* main_path = format("%s/main.c", src_dir);

	char* include_dir = format("%s/.includes", directory);
	char* libraries_dir = format("%s/.libraries", directory);

	if (directory_exists(project_name))
		return PROJECT_DIR_ALREADY_EXISTS;

	directory_create(project_name);

	file_t ini_file = file_open(ini_path, WRITE_BINARY);
	fprintf(ini_file, CUTE_INI, project_name);
	file_close(ini_file);

	file_t lock_file = file_open(lock_path, WRITE_BINARY);
	fprintf(lock_file, CUTE_LOCK_INI);
	file_close(lock_file);

	file_t cmakelists_txt_file = file_open(cmakelists_txt_path, WRITE_BINARY);
	fprintf(cmakelists_txt_file, CMAKELISTS_TXT, project_name);

	directory_create(src_dir);

	file_t main_file = file_open(main_path, WRITE_BINARY);
	fprintf(main_file, MAIN_C);
	file_close(main_file);

	free(directory);
	free(ini_path);
	free(lock_path);
	free(cmakelists_txt_path);
	free(src_dir);
	free(main_path);
	free(include_dir);
	free(libraries_dir);

	return PROJECT_SUCCESS;
}

